#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'

export PATH=$PATH:/home/prakarsh/anaconda3/bin:/home/prakarsh/anaconda3/condabin:/home/prakarsh/All_courses/missing_semester_mit/test_add_shebang

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/prakarsh/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/prakarsh/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/prakarsh/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/prakarsh/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

force_color_prompt=yes
export TERM=xterm-256color
alias tmux='tmux -u -2'

